### PR TITLE
Change rules for merging PRs in the main OpenMage repo

### PR DESCRIPTION
**Pull request by fballiano**
We've been discussing it for a while, I think we can speed up the PR merging procedures and times, but I also think that this new method could help more contributors feel useful and thus maybe participate more.

### CODE REVIEW

**Comment by addison74** [comment]
Mainly I agree this and I will revise in the next period. 

Use a spell checker for the text. There are a few misspellings. E.g. "reviewd", "mainteiners", "apporval", "approvation", "stagnat", "timezones", "markes", "wouldn't meed".

**Review by Flyingmana — APPROVED** [review]

**Comment by fballiano** [comment]
updated, fixed some typos

**Review by kiatng — APPROVED** [review]
This is great! Thank you for your works!

**Comment by luigifab** [comment]
The alt of the image is wrong: `Schermata 2021-12-20 alle 15 01 47` :)

**Comment by Sekiphp** [comment]
I read your proposal RFC and I cannot approve it in current form. Why?

## Reasons
1. `has 4 positive reviews by normal users (4 gray checks)` 
This can be very, **very dangerous!** Especially for me is very important, that OpenMage is very stable platform, on which I running multiple huge e-commerce sites. In my opinion, approve from maintainers is something like guarantee of quality. All maintainers are experienced Magento 1 & OpenMage developers with deeply knowledge of platform. On the other hand someone can create "shitty" PR and can get approve from colleagues from the company (4 gray checks).

2. `has 1 positive review by a maintainer and at 2 by normal users (1 green check + 2 gray checks)`
Can we change is to 1 green check + 4 gray checks? I'm not sure about this rule as well, but 4 gray checks make bigger sense to me. But... sometimes it happening, that one maintainer gives approve and other requesting changes :-)

**Review by Sekiphp — CHANGES_REQUESTED** [review]
I read your proposal RFC and I cannot approve it in current form. Why?

## Reasons
1. `has 4 positive reviews by normal users (4 gray checks)` 
This can be very, **very dangerous!** Especially for me is very important, that OpenMage is very stable platform, on which I running multiple huge e-commerce sites. In my opinion, approve from maintainers is something like guarantee of quality. All maintainers are experienced Magento 1 & OpenMage developers with deeply knowledge of platform. On the other hand someone can create "shitty" PR and can get approve from colleagues from the company (4 gray checks).

2. `has 1 positive review by a maintainer and at 2 by normal users (1 green check + 2 gray checks)`
Can we change is to 1 green check + 4 gray checks? I'm not sure about this rule as well, but 4 gray checks make bigger sense to me. But... sometimes it happening, that one maintainer gives approve and other requesting changes :-)

**Comment by midlan** [comment]
Agree with @Sekiphp . I would hire more maintiners. I saw in PRs there are people producing quaility code repeatedly and still not maintiners.

**Comment by Flyingmana** [comment]
We could ease this 4 gray checks part, by specifically only allow manual merges, no automatic merges there.
Because, even if someone merging does not approve, before merging would be required to check the code for risks and problems.
Also we are not necessarily limited to green/gray checks here, just because this is what github offers. We can have a separate list of trusted reviewers which we could see as "yellow" checks?
Thats easy to do with such a rendered list (I really like this list, I already did go through it a few times to easier find the PRs with many approves already)

**Comment by fballiano** [comment]
> 1. `has 4 positive reviews by normal users (4 gray checks)`

that was discussed in the discussion area and it wasn't even my idea...

> 2. `has 1 positive review by a maintainer and at 2 by normal users (1 green check + 2 gray checks)`
>    Can we change is to 1 green check + 4 gray checks? I'm not sure about this rule as well, but 4 gray checks make bigger sense to me. But... sometimes it happening, that one maintainer gives approve and other requesting changes :-)

again, if I remember correctly it was a proposal from another maintainer.

my original idea was to create a group of non-maintainer trusted-users with more than X merged PR, that would count as maintainers. but I got objections and also github doens't have anything like that so...

It was discussed for long and the feedback was what I ended up putting in this PR.

**Comment by fballiano** [comment]
also, what's the rule for becoming a maintainer and how many maintainers are there?
because from outside it kinda seem the inner circle is closed, no new maintainers are really welcome (when did the last one join? was it communicated in some way?) but at the same time just 2-3 maintainers participate in the PRs (I obviously get the time problem it implies) and that is why we have 200 PRs and 300 issues.

I'm just trying to move the freaking water, if it stagnate the project will die.

If you maintainers have other opinions please decide something that will help everybody speed up to process of merging or closing the PRs, but it's a bit disappointing (after the whole thread in the discussion area) to see such different opinions now and it's pretty clear nobody is happy with the current flow.

**Comment by fballiano** [comment]
Hi everybody, from what I read in the https://github.com/OpenMage/rfcs#readme something should happed when the PR is at least 2 months old, am I right?

**Comment by Flyingmana** [comment]
you are right, thank you for reminding

**Comment by fballiano** [comment]
thank you! now that's been merged I see that it needs 10 votes, but where should people vote?

**Comment by Flyingmana** [comment]
yeah, good question.
I would say in a new PR, which ads the RFC to accepted, and via comments.
Also, will we just vote for Accept/Not-Accept for the whole one, or also for some details of it?

**Pull request merged**
